Aplicatie_fara_sistem_auth/BiblioTECH/Controllers/BranchController.cs
using BiblioTECH.Models.Branch;
using BiblioTECH.WebServices.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using TechData.Interfaces;
using TechData.Models;

namespace BiblioTECH.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BranchController : Controller
    {
        private readonly ILibraryBranchService _branchService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IWebService _webService;

        public BranchController(ILibraryBranchService branchService, IWebHostEnvironment hostingEnvironment, IWebService webService)
        {
            _branchService = branchService;
            _hostingEnvironment = hostingEnvironment;
            _webService = webService;
        }


        [HttpGet]
        public IActionResult Add()
        {
            //Trebuie customizat
            return View();
        }

        [HttpPost]
        public IActionResult PlaceAdd(AddBranchModel model)
        {

            var branch = new LibraryBranch
            {
                Name = model.Name,
                Address = model.Address,
                Telephone = model.Telephone,
                Description = model.Description,
                ImageUrl = _webService.CopyBranchPhoto(model.Image),
                OpenDate = DateTime.Now
            };
            _branchService.Add(branch);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var branch = _branchService.Get(id);
            var model = new EditBranchModel
            {
                BranchId = id,
                Name = branch.Name,
                Address = branch.Address,
                Telephone = branch.Telephone,
                Description = branch.Description
            };
            return View(model);
        }


        [HttpPost]
        public IActionResult PlaceEdit(EditBranchModel model)
        {
            var editedBranch = _branchService.Get(model.BranchId);
            editedBranch.Name = model.Name;
            editedBranch.Address = model.Address;
            editedBranch.Telephone = model.Telephone;
            editedBranch.Description = model.Description;
            editedBranch.ImageUrl = model.Image == null ? editedBranch.ImageUrl : _webService.CopyBranchPhoto(model.Image);

            _branchService.Edit(editedBranch);

            return RedirectToAction("index");
        }



        [HttpGet]
        public IActionResult Delete(int id)
        {
            //Trebuie customizat
            return View();
        }

        [HttpPost]
        public IActionResult PlaceDelete(int id)
        {
            _branchService.Delete(id);
            return RedirectToAction("Index");
        }




        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            var branchModels = _branchService.GetAll()
                .Select(br => new BranchDetailModel
                {
                    Id = br.Id,
                    BranchName = br.Name,
                    NumberOfAssets = _branchService.GetAssetCount(br.Id),
                    NumberOfPatrons = _branchService.GetPatronCount(br.Id),
                    IsOpen = _branchService.IsBranchOpen(br.Id)
                }).ToList();

            var model = new BranchIndexModel
            {
                Branches = branchModels
            };

            return View(model);
        }



        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(int id)
        {
            //IEnumerable<string>TimeTable = new List<string>() {}
            var branch = _branchService.Get(id);
            var model = new BranchDetailModel
            {
                Id = id,
                BranchName = branch.Name,
                Description = branch.Description,
                Address = branch.Address,
                Telephone = branch.Telephone,
                BranchOpenedDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = _branchService.GetPatronCount(id),
                NumberOfAssets = _branchService.GetAssetCount(id),
                TotalAssetValue = _branchService.GetAssetsValue(id),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branchService.GetBranchHours(id)
            };

            return View(model);
        }
    }
}

Aplicatie_fara_sistem_auth/BiblioTECH/Controllers/PatronController.cs
using BiblioTECH.Models.Patron;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechData.Interfaces;
using TechData.Models;

namespace BiblioTECH.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PatronController : Controller
    {
        private readonly IPatronService _patronService;
        private readonly UserManager<ApplicationUser> _userManager;

        public PatronController(IPatronService patronService, UserManager<ApplicationUser> userManager)
        {
            _patronService = patronService;
            _userManager = userManager;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var allPatrons = _patronService.GetAll();

            var patronModels = allPatrons
                .Select(p => new PatronDetailModel
                {
                    Id = p.Id,
                    LastName = p.LastName ?? "No First Name Provided",
                    FirstName = p.FirstName ?? "No Last Name Provided",
                    LibraryCardId = p.LibraryCard?.Id,
                    OverdueFees = p.LibraryCard?.Fees,
                    HomeLibrary = p.HomeLibraryBranch?.Name,


                }).ToList();

            var model = new PatronIndexModel
            {
                Patrons = patronModels
            };

            return View(model);
        }


        [HttpGet]
        public IActionResult Detail(int id)
        {
            var patron = _patronService.Get(id);

            var model = new PatronDetailModel
            {
                Id = patron.Id,
                LastName = patron.LastName ?? "No Last Name Provided",
                FirstName = patron.FirstName ?? "No First Name Provided",
                Address = patron.Address ?? "No Address Provided",
                HomeLibrary = patron.HomeLibraryBranch?.Name ?? "No Home Library",
                MemberSince = patron.LibraryCard?.Created,
                OverdueFees = patron.LibraryCard?.Fees,
                LibraryCardId = patron.LibraryCard?.Id,
                Telephone = string.IsNullOrEmpty(patron.Telephone) ? "No Telephone Number Provided" : patron.Telephone,
                AssetsCheckedOut = _patronService.GetCheckouts(id).ToList(),
                CheckoutHistory = _patronService.GetCheckoutHistory(id),
                Holds = _patronService.GetHolds(id),
                Email = patron.Email ?? "No Email Provided"
            };

            return View(model);
        }

        [AllowAnonymous]
        public IActionResult Add()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var user = _userManager.Users
                .First(us => us.Id == userId);
            var newPatron = new Patron
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                DateOfBirth = user.DateOfBirth,
                Telephone = user.Telephone,
                Gender = user.Gender,
                Email = user.Email
            };

            int branchId = int.Parse(user.HomeBranch);

            _patronService.Add(newPatron, branchId);

            return RedirectToAction("Index","Catalog");
        }
    }
}

Aplicatie_fara_sistem_auth/BiblioTECH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@using TechData.Models
@inject SignInManager<ApplicationUser> SignInManager

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LightLib Library Management System</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">


    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />


    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/FontAwesome 5.13.0/css/all.min.css" rel="stylesheet" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title logo"><a href="/">LightLib</a></span>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                        <a class="mdl-navigation__link" asp-controller="Administration" asp-action="ListRoles">Drepturi User</a>
                    }
                    <!-- Add spacer, to align navigation to the right -->
                    <div class="mdl-layout-spacer"></div>

                    @*If the user is signed-in display Logout link*@
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <form method="post" asp-controller="Account" asp-action="logout">
                            <button type="submit" style="width:auto"
                                    class="nav-link btn btn-link py-0">
                                Logout @User.Identity.Name
                            </button>
                        </form>
                    }
                    else
                    {

                        <a class="mdl-navigation__link" asp-controller="Account" asp-action="register">
                            Register
                        </a>
                        <a class="mdl-navigation__link" asp-controller="Account" asp-action="login">
                            LogIn
                        </a>
                    }

                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">LightLib</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
            </nav>
        </div>
        <div class="page-content">
            @RenderBody()
        </div>
    </div>

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)

</body>
</html>